# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cust_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=20)),
                ('cust_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cust_details',
            },
        ),
    ]
